[package]
name = "ichor"
version = "0.1.0"
edition = "2018"
authors = ["fuderiki <frederic@designlab.ac>"]
description = "High-performance AI game algorithms in Rust with C# and C++ bindings for Unity and Unreal"
license = "MIT"

[dependencies]
wgpu = "0.15.1"
futures = "0.3.27"
tokio = { version = "1.26.0", features = ["full"] }
rayon = "1.7.0"
num-traits = "0.2.15"


[build-dependencies]
shaderc = "0.8.2"

[features]
default = []
